server:
  port: 8082

spring:
  application:
    name: bff

usuario:
  service:
    url: http://localhost:8080

notificacao:
  service:
    url: http://localhost:8083

agendador:
  service:
    url: http://localhost:8081

springdoc.show-actuator: true